name: CI
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -U pip
          python -m pip install -r requirements.txt
          # Robot Framework Browser initialisieren (Playwright + Deps)
          python -m Browser.entry init

      - name: Ensure reports dir exists
        run: mkdir -p reports

      - name: Run Robot tests
        env:
          STANDARD_USER: ${{ secrets.STANDARD_USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LOCKED_OUT_USER: ${{ secrets.LOCKED_OUT_USER }}
          INVALID_USER: ${{ secrets.INVALID_USER }}
          INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          source .venv/bin/activate
          # Falls deine Tests ${BROWSER} erwarten, hier ein Default:
          # ROBOT_ARGS="-v BROWSER:chromium"
          robot \
            --outputdir reports \
            --xunit reports/junit.xml \
            --pythonpath libs \
            -V variables/env_or_file.py \
            tests/

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-reports
          path: reports/
          if-no-files-found: warn
